name: Build "turnip"

on:
  workflow_dispatch:
  schedule:
  - cron: "20 5 1,15 * *"

jobs:
  start_building_turnip:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt update
        sudo apt build-dep mesa -y
        sudo sed -i 's/jammy/mantic/g' /etc/apt/sources.list
        sudo apt update
        sudo apt install meson

    - name: Execute build script
      run: bash ./turnip_builder.sh

    - name: Upload build logs
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Build logs
        path: |
          turnip_workdir/ninja_log
          turnip_workdir/mesa-main/build-android-aarch64/meson-logs/meson-log.txt

    - name: Upload Turnip
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Turnip
        path: turnip_workdir/turnip.zip

    
